version: '3'
services:
  php-apache:
      container_name: php-apache-environment
      build:
        context: .
        dockerfile: Dockerfile-php
      volumes:
      - ./php/src:/var/www/html/:rw
      ports:
        - 8005:80
      networks:
          - app-network
  db:
        container_name: db
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_USER: ROOT
            MYSQL_ROOT_PASSWORD: ROOT
            MYSQL_DATABASE: MYSQL_DATABASE
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
        volumes:
          - ./db-data:/var/lib/mysql:rw
        ports:
          - "9906:3306"
        networks:
          - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - app-network
    ports:
        - '8080:80'
    restart: always
    environment:
        PMA_HOST: db
        UPLOAD_LIMIT: 300M
    depends_on:
        - db
networks:
  app-network:
    driver: bridge
